// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgYTHnsmaiYHIok0L3SMGehp7y5lL2ss',
    appId: '1:608661761832:web:8e0960d6678f99bb5d2a1d',
    messagingSenderId: '608661761832',
    projectId: 'flutter-authentication-6a415',
    authDomain: 'flutter-authentication-6a415.firebaseapp.com',
    storageBucket: 'flutter-authentication-6a415.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvoAdiCudRSt5rcEqKPaK9-VUJLJvmc4g',
    appId: '1:608661761832:android:9e39c07954f3c6875d2a1d',
    messagingSenderId: '608661761832',
    projectId: 'flutter-authentication-6a415',
    storageBucket: 'flutter-authentication-6a415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg0a0fPE57WKoRutVL_z-Pbx_CDuDO3fA',
    appId: '1:608661761832:ios:587541fec54ab1b65d2a1d',
    messagingSenderId: '608661761832',
    projectId: 'flutter-authentication-6a415',
    storageBucket: 'flutter-authentication-6a415.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg0a0fPE57WKoRutVL_z-Pbx_CDuDO3fA',
    appId: '1:608661761832:ios:587541fec54ab1b65d2a1d',
    messagingSenderId: '608661761832',
    projectId: 'flutter-authentication-6a415',
    storageBucket: 'flutter-authentication-6a415.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRgYTHnsmaiYHIok0L3SMGehp7y5lL2ss',
    appId: '1:608661761832:web:976b25ed37e3de8d5d2a1d',
    messagingSenderId: '608661761832',
    projectId: 'flutter-authentication-6a415',
    authDomain: 'flutter-authentication-6a415.firebaseapp.com',
    storageBucket: 'flutter-authentication-6a415.firebasestorage.app',
  );
}
